### ISSUE TITLE
Magento 2 connect error

### ISSUE THREAD

**Issue by igmltd** [printful/magento2-module#5]
Module does not work with the latest version of magento, fails on activate with the following message:

**Magento 2 connect error: Could not find connection data! Please check that your store is accessible, try again or contact Printful support!**

https://github.com/user-attachments/assets/5ec39c53-529d-4655-8616-b2c90cc88d71

**Comment by igmltd** [comment]
it was due to the ip address of printful blocked by our firewall.

**Comment by J-Wick4** [comment]
Can I get a confirmation that this module is working with the latest version of Magento?

**Comment by igmltd** [comment]
Seems to be working just fine on the latest version.
